name: Pipeline
on:
    push:
        branches: 
            - master

jobs: 
    deploy:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: install dependencies
              run: npm install
            - name: Deploy to heroku
              uses: akhileshns/heroku-deploy@v3.13.15  
              with:
                heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                heroku_app_name: ${{secrets.HEROKU_APP}}
                heroku_email: ${{secrets.HEROKU_API_EMAIL}}